<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config = array();
$config['protocol']= 'smtp';
$config['smtp_host']='ssl://smtp.googlemail.com';
$config['smtp_port']= '465';
$config['smtp_timeout']='30';
$config['smtp_user']= 'thuan.nguyenngockim@gmail.com';
$config['smtp_pass']= '08158291';
$config['charset']= 'utf-8';
$config['newline']= '\r\n';